[versions]
compileSdkVersion = "35" # Int
buildToolsVersion = "29.0.2"
minSdkVersion = "28" # Int
targetSdkVersion = "35" # Int
versionCode = "146" # Int
versionName = "3.250213.0"
kotlinCompilerExtensionVersion = "1.5.15"
jvmTarget = "17"
javaVersion = "VERSION_17" # JavaVersion.VERSION_17
ksp = "2.1.20-Beta1-1.0.29"

agp = "8.7.3"
androidx-baselineprofile-version = "1.3.3"
kotlin-version = "2.1.20-Beta1"
kotlin-serialization-gradle = "2.1.20-Beta1"
androidx-test-core = "1.6.1"
androidx-test-rules = "1.6.1"
androidx-test-runner = "1.6.2"
androidx-compose-ui-test = "1.7.7"
androidx-compose-ui = "1.6.7"
androidx-lifecycle = "2.8.7"
compose-bom = "2024.12.01"

androidx-activity = "1.9.3"
androidx-appcompat = "1.7.0"
androidx-core-ktx = "1.15.0"
androidx-core-splashscreen = "1.1.0-rc01"
androidx-annotation = "1.9.1"
androidx-navigation-ui-kotlin = "2.8.6"
androidx-gridlayout = "1.0.0"
androidx-profile-installer = "1.4.1"
androidx-biometric = "1.4.0-alpha02"

ktor-version = "3.0.3"

kotlinx-coroutines-version = "1.10.1"
kotlinx-datetime-version = "0.6.1"
kotlinx-atomicfu-version = "0.27.0"
kotlinx-io-version = "0.6.0"
kotlinx-html-version = "0.11.0"
okio-version = "3.10.2"
cryptography-version = "0.3.0"
ksoup-html-version = "0.5.0"

accompanist = "0.37.0"
google-material = "1.12.0"
coil-version = "3.1.0"
camera-version = "1.4.1"
camera-barcode = "17.3.0"
camera-zxing = "3.5.3"
commons-compress = "1.26.1"
jetbrains-compose-version = "1.7.3"
jetbrains-androidx-navigation-version = "2.8.0-alpha11"
jetbrains-compose-material3-adaptive-version = "1.0.1"

# 测试
test-junit = "5.10.1"
animation-core-android = "1.7.7"
material3Android = "1.3.1"

kotlinx-serialization = "1.8.0"

#jxbrowser-version = "8.0.0-eap.+"
jxbrowser-version = "8.3.0"
jxbrowser-gradle = "1.2.1"

# jna
java-jna-version = "5.14.0"
webkit = "1.12.1"

junit = "1.2.1"
espresso = "3.6.1"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.3.3"
roomKtx = "2.6.1"
log4j12 = "2.0.12"

filekit = "0.8.0"

dweb-version = "1.0.0"

[libraries]

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material_icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Android" }

# Jetbrains Compose
jetbrains-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose-version" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose-version" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose-version" }
jetbrains-compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jetbrains-compose-version" }
jetbrains-compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "jetbrains-compose-version" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrains-compose-version" }
jetbrains-compose-material3-window-size = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "jetbrains-compose-version" }
jetbrains-compose-materialIcons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "jetbrains-compose-version" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose-version" }
jetbrains-compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "jetbrains-compose-version" }
jetbrains-compose-ui-tooling-preview-desktop = { module = "org.jetbrains.compose.ui:ui-tooling-preview-desktop", version.ref = "jetbrains-compose-version" }
jetbrains-compose-ui-test-junit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "jetbrains-compose-version" }
jetbrains-androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-androidx-navigation-version" }
jetbrains-compose-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "jetbrains-compose-material3-adaptive-version" }
jetbrains-compose-material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "jetbrains-compose-material3-adaptive-version" }
jetbrains-compose-material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "jetbrains-compose-material3-adaptive-version" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-navigation-ui-kotlin = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation-ui-kotlin" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "androidx-gridlayout" }
androidx-profile-installer = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidx-profile-installer" }
androidx-animation-core-android = { group = "androidx.compose.animation", name = "animation-core-android", version.ref = "animation-core-android" }

kotlinx-coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines-version" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-version" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines-version" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime-version" }
kotlinx-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "kotlinx-atomicfu-version" }
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io-version" }
kotlinx-html = { group = "org.jetbrains.kotlinx", name = "kotlinx-html", version.ref = "kotlinx-html-version" }
squareup-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio-version" }
squareup-okio-nodefilesystem = { group = "com.squareup.okio", name = "okio-nodefilesystem", version.ref = "okio-version" }
squareup-okio-fakefilesystem = { group = "com.squareup.okio", name = "okio-fakefilesystem", version.ref = "okio-version" }
whyoleg-cryptography-core = { group = "dev.whyoleg.cryptography", name = "cryptography-core", version.ref = "cryptography-version" }
whyoleg-cryptography-provider-jdk = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-jdk", version.ref = "cryptography-version" }
whyoleg-cryptography-provider-webcrypto = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-webcrypto", version.ref = "cryptography-version" }
whyoleg-cryptography-provider-apple = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-apple", version.ref = "cryptography-version" }
whyoleg-cryptography-provider-openssl3-api = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-openssl3-api", version.ref = "cryptography-version" }
whyoleg-cryptography-provider-openssl3-shared = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-openssl3-shared", version.ref = "cryptography-version" }
whyoleg-cryptography-provider-openssl3-prebuilt = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-openssl3-prebuilt", version.ref = "cryptography-version" }
mohamedrejeb-ksoup-html = { group = "com.mohamedrejeb.ksoup", name = "ksoup-html", version.ref = "ksoup-html-version" }

# ktor
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets", version.ref = "ktor-version" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor-version" }
ktor-server-host-common = { group = "io.ktor", name = "ktor-server-host-common", version.ref = "ktor-version" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor-version" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor-version" }
ktor-server-jetty = { group = "io.ktor", name = "ktor-server-jetty-jakarta", version.ref = "ktor-version" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor-version" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor-version" }
ktor-client-jetty = { group = "io.ktor", name = "ktor-client-jetty", version.ref = "ktor-version" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor-version" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor-version" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor-version" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor-version" }
ktor-io = { group = "io.ktor", name = "ktor-io", version.ref = "ktor-version" }
ktor-http = { group = "io.ktor", name = "ktor-http", version.ref = "ktor-version" }
ktor-network-tls-certificates = { group = "io.ktor", name = "ktor-network-tls-certificates", version.ref = "ktor-version" }

accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
# 数据 json
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-serialization-cbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor", version.ref = "kotlinx-serialization" }
# 加载图片 coil
coil-core = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil-version" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-version" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil-version" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil-version" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video", version.ref = "coil-version" }
coil-gif = { group = "io.coil-kt.coil3", name = "coil-gif", version.ref = "coil-version" }
# 扫码核心库
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera-version" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera-version" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera-version" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera-version" }
camera-barcode = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "camera-barcode" }
camera-zxing-code = { group = "com.google.zxing", name = "core", version.ref = "camera-zxing" }
camera-zxing-javase = { group = "com.google.zxing", name = "javase", version.ref = "camera-zxing" }
# 解压文件
apache-common-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commons-compress" }
# 生物识别
androidx-biometric-ktx = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "androidx-biometric" }

# 测试相关
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test-core" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test", version.ref = "androidx-compose-ui-test" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose-ui-test" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose-ui-test" }
test-kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-version" }
test-kotlin-coroutines-debug = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version.ref = "kotlinx-coroutines-version" }
test-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
test-junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-test-espresso-web = { group = "androidx.test.espresso", name = "espresso-web", version.ref = "espresso" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
org-slf4j-log4j12 = { group = "org.slf4j", name = "slf4j-log4j12", version.ref = "log4j12" }

# 文件选择器
filekit-compose = { group = "io.github.vinceglb", name = "filekit-compose", version.ref = "filekit" }

# jna
java-jna = { module = "net.java.dev.jna:jna", version.ref = "java-jna-version" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }

gradlePlugin-android = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradlePlugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-version" }
gradlePlugin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin-serialization-gradle" }
gradlePlugin-jetbrainsCompose = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "jetbrains-compose-version" }
gradlePlugin-composeCompiler = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin-version" }
gradlePlugin-jxbrowser = { group = "com.teamdev.jxbrowser", name = "jxbrowser-gradle-plugin", version.ref = "jxbrowser-gradle" }
# pinpit 用于桌面端多平台打包
gradlePlugin-pinpit = { group = "de.mobanisto.pinpit", name = "pinpit-gradle-plugin", version = "0.9.0" }

# ksp
gradlePlugin-ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
google-devtools-ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

# 解析plist文件
dd-plist = { group = "com.googlecode.plist", name = "dd-plist", version = "1.28" }

# dweb library
dweb-biometrics = { group = "io.github.dweb-channel", name = "lib_biometrics", version.ref = "dweb-version" }
dweb-ziplib = { group = "io.github.dweb-channel", name = "lib_ziplib", version.ref = "dweb-version" }
dweb-reverse-proxy = { group = "io.github.dweb-channel", name = "lib_reverse_proxy", version.ref = "dweb-version" }
dweb-hardware-info = { group = "io.github.dweb-channel", name = "lib_hardware_info", version.ref = "dweb-version" }
dweb-keychainstore = { group = "io.github.dweb-channel", name = "lib_keychainstore", version.ref = "dweb-version" }
dweb-mix-compression = { group = "io.github.dweb-channel", name = "lib_mix_compression", version.ref = "dweb-version" }
dweb-multipart = { group = "io.github.dweb-channel", name = "lib_multipart", version.ref = "dweb-version" }
dweb-resvg-render = { group = "io.github.dweb-channel", name = "lib_resvg_render", version.ref = "dweb-version" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidxBaselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-baselineprofile-version" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinxMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-version" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }


[bundles]
